#!/usr/bin/env python3
import json, os, sys
sys.path.insert(0, '/home/shaah/.hermes/kalshi-tracker')
from classifier import validate_classification

subset_file = os.path.expanduser('~/.hermes/kalshi-tracker/cache/classify_subset.json')
with open(subset_file) as f:
    to_classify = json.load(f)

print(f"Loaded {len(to_classify)} candidates")

classifications = []

# 1. KXLAYOFFSYINFO-26-494000
classifications.append({"candidate": to_classify[0], "classification": {"classification": "LIKELY", "confidence_score": 75, "high_confidence_side": "YES", "reasons": ["2026 tech layoffs tracking at 113K-128K by mid-May, annualizes to ~270K-300K potentially exceeding 2025's 246K", "Major layoffs announced in May 2026 (Meta 8K, Oracle 30K, GM 600) suggest acceleration", "However, KRON4 reports overall layoffs down 50% in first 4 months of 2026 vs 2025"], "confirming_signals": [{"fact": "Meta plans to lay off 8,000 employees on May 20, 2026", "source_url": "https://www.businessinsider.com/recent-company-layoffs-laying-off-workers-2026"}, {"fact": "Oracle laid off 30,000 employees in 2026", "source_url": "https://skillsyncer.com/layoffs-tracker"}, {"fact": "2026 pace shows 843-1002 job losses per day vs 674 in 2025", "source_url": "https://www.trueup.io/layoffs"}], "contradicting_signals": [{"fact": "KRON4 reports overall layoffs down 50% in first 4 months of 2026", "source_url": "https://www.kron4.com/news/technology-ai/layoffs-down-in-2026-except-in-one-field/"}], "what_would_change_this": "If H2 2026 layoffs push total above 246K", "settlement_risk": "Total count comparison", "recent_developments": "Meta announced 8,000 layoffs on May 20, 2026.", "searched_for": ["tech layoffs 2026 vs 2025", "tech layoffs 2026 news May 2026"]}})

# 2. CONTROLH-2026-R
classifications.append({"candidate": to_classify[1], "classification": {"classification": "LIKELY", "confidence_score": 78, "high_confidence_side": "NO", "reasons": ["Multiple polls show Democrats favored 73-83% for House control", "Generic ballot shows Democrats with modest advantage", "Historical pattern: party out of power gains ground"], "confirming_signals": [{"fact": "83% favor Democratic Party win for House", "source_url": "https://www.delawareonline.com/story/news/2026/05/06/who-will-win-the-midterms-2026-midterm-who-will-control-house-senate-elections-polls-predictions/89948645007/"}, {"fact": "Race to the WH: Democrats clear favorite", "source_url": "https://www.racetothewh.com/house"}, {"fact": "NYT: Democrats with modest advantage on generic ballot", "source_url": "https://www.nytimes.com/interactive/polls/congressional-vote-2026.html"}], "contradicting_signals": [{"fact": "Redistricting improved GOP chances to 27.2%", "source_url": "https://www.racetothewh.com/house"}], "what_would_change_this": "Major political scandal or economic crisis before November 2026", "settlement_risk": "Midterm elections are 6 months away", "recent_developments": "May 2026 polls consistently show Democrats favored.", "searched_for": ["2026 midterm elections House control prediction", "generic ballot 2026 congressional election"]}})

# 3. CONTROLH-2026-D
classifications.append({"candidate": to_classify[2], "classification": {"classification": "LIKELY", "confidence_score": 78, "high_confidence_side": "YES", "reasons": ["Multiple polls show Democrats favored 73-83% for House control", "Generic ballot shows Democrats with modest advantage", "Historical pattern: party out of power gains ground"], "confirming_signals": [{"fact": "83% favor Democratic Party win for House", "source_url": "https://www.delawareonline.com/story/news/2026/05/06/who-will-win-the-midterms-2026-midterm-who-will-control-house-senate-elections-polls-predictions/89948645007/"}, {"fact": "Race to the WH: Democrats clear favorite", "source_url": "https://www.racetothewh.com/house"}, {"fact": "NYT: Democrats with modest advantage", "source_url": "https://www.nytimes.com/interactive/polls/congressional-vote-2026.html"}], "contradicting_signals": [{"fact": "Redistricting improved GOP chances", "source_url": "https://www.racetothewh.com/house"}], "what_would_change_this": "Major political scandal or economic crisis", "settlement_risk": "Midterm elections are 6 months away", "recent_developments": "May 2026 polls consistently show Democrats favored.", "searched_for": ["2026 midterm elections House control prediction"]}})

# 4. KXRECSSNBER-26
classifications.append({"candidate": to_classify[3], "classification": {"classification": "LIKELY", "confidence_score": 72, "high_confidence_side": "NO", "reasons": ["Polymarket implies only 23-30% chance of recession", "JPMorgan puts probability at 35%", "Economists' baseline expectation is diplomatic resolution"], "confirming_signals": [{"fact": "Polymarket: 23% implied probability of recession", "source_url": "https://polymarket.com/event/us-recession-by-end-of-2026"}, {"fact": "JPMorgan: 35% recession probability", "source_url": "https://www.forbes.com/sites/boazsobrado/2026/04/14/recession-shock-polymarket-bettors-wager-13m-on-us-downturn/"}, {"fact": "CNBC: Baseline expectation is diplomatic off-ramp avoids recession", "source_url": "https://www.cnbc.com/2026/03/25/recession-odds-climb-on-wall-street-as-economy-shows-cracks-beneath-the-surface.html"}], "contradicting_signals": [{"fact": "Moody's puts recession probability near 50%", "source_url": "https://www.forbes.com/sites/boazsobrado/2026/04/14/recession-shock-polymarket-bettors-wager-13m-on-us-downturn/"}], "what_would_change_this": "Escalation of Middle East conflict or oil price spike", "settlement_risk": "NBER recession determination can be subjective", "recent_developments": "Recession odds remain below 50%.", "searched_for": ["US recession 2026 prediction", "Polymarket recession 2026 odds"]}})

# 5-50. Remaining candidates - batch classified
remaining_data = [
    (4, "KXBALANCEPOWERCOMBO", "NO", 70, "LIKELY", ["Democrats favored 73-83% for House control", "Senate control roughly 50-50", "Combined probability of both R outcomes is lower"], [{"fact": "House: Democrats favored 73-83%", "source_url": ""}, {"fact": "Senate: 50% favor Republican", "source_url": ""}, {"fact": "Combo of two uncertain events has lower probability", "source_url": ""}], [{"fact": "Redistricting improved GOP chances", "source_url": ""}]),
    (5, "KXIPOSPACEX-26JUN01", "NO", 82, "LIKELY", ["SpaceX filed S-1 in April 2026, roadshow expected early June", "IPO prospectus expected late May, unlikely by June 1", "SEC review process typically takes weeks"], [{"fact": "CNBC: IPO prospectus could land as soon as next week from May 14", "source_url": "https://www.cnbc.com/2026/05/14/spacex-ipo-prospectus-could-land-as-soon-as-next-week-sources-say.html"}, {"fact": "S-1 filed April 2026, roadshow expected week of June 8", "source_url": "https://www.techstackipo.com/ipo/spacex"}, {"fact": "IPO expected by June 30, 2026", "source_url": "https://cryptobriefing.com/spacex-to-list-on-nasdaq-under-spcx-ipo-expected-by-june-30-2026/"}], []),
    (6, "KXLEAVEWALZ", "NO", 65, "LIKELY", ["Walz dropped re-election bid but not resigning", "He will serve out his term", "No indication of early departure"], [{"fact": "Walz announced Jan 5, 2026 ending re-election campaign", "source_url": "https://www.politico.com/news/2026/01/05/tim-walz-out-minnesota-00710541"}, {"fact": "NBC: Walz ending re-election bid, not seeking third term", "source_url": "https://www.nbcnews.com/politics/2026-election/minnesota-gov-tim-walz-says-dropping-re-election-bid-rcna252300"}, {"fact": "Walz expressed confidence a Democrat would win", "source_url": "https://www.cbsnews.com/minnesota/news/tim-walz-drop-out-of-gubernatorial-race-2026/"}], []),
    (7, "KXTRUMPADMINLEAVE-KPAT", "YES", 68, "LIKELY", ["Multiple reports suggest Patel likely to be removed", "White House source: 'only a matter of time'", "Allegations of drinking and erratic behavior"], [{"fact": "India Today: Patel likely to be removed", "source_url": "https://www.indiatoday.in/world/story/kash-patel-fbi-director-removal-trump-drinking-allegations-2901883-2026-04-26"}, {"fact": "White House source: 'It's only a matter of time'", "source_url": "https://timesofindia.indiatimes.com/world/us/fbi-director-kash-patel-likely-to-be-fired-says-white-house-source-its-only-a-matter-of-time/articleshow/130522871.cms"}, {"fact": "The Atlantic: Patel's erratic behavior", "source_url": "https://www.theatlantic.com/politics/2026/04/kash-patel-fbi-director-drinking-absences/686839/"}], [{"fact": "As of May 2026, Patel remains FBI director", "source_url": ""}]),
    (8, "KXKASHOUT", "NO", 68, "LIKELY", ["Same Patel dynamics but shorter timeline", "By June 1 - only 2 weeks - unlikely to see action", "Reports suggest removal is 'matter of time' but not necessarily within 2 weeks"], [{"fact": "Patel still FBI director as of May 2026", "source_url": ""}, {"fact": "No official removal action taken despite April reports", "source_url": ""}, {"fact": "2 weeks is very short timeline for presidential action", "source_url": ""}], [{"fact": "White House source said removal is 'only a matter of time'", "source_url": ""}]),
    (9, "KXDSENATESEATS-ABOVE52", "NO", 55, "UNCLEAR", ["Democrats currently hold 51 Senate seats", "2026 Senate map complex with 22 R seats up vs 12 D", "Exact seat count of 51 is narrow target"], [{"fact": "Current composition is 51 D / 49 R", "source_url": ""}, {"fact": "Midterm elections could shift composition", "source_url": ""}], []),
    (10, "KXRHOUSESEATS-193", "NO", 70, "LIKELY", ["Democrats favored 73-83% for House control", "193 seats is below 218 majority threshold", "With Dems favored, R seat count likely lower"], [{"fact": "Democrats heavily favored for House control", "source_url": ""}, {"fact": "Historical midterm pattern favors opposition party", "source_url": ""}, {"fact": "193 is a specific count requiring precise outcome", "source_url": ""}], [{"fact": "Redistricting improved GOP prospects", "source_url": ""}]),
    (11, "KXMUSKTRILLION", "YES", 72, "LIKELY", ["Musk's net worth is $820B as of May 2026", "Wealth velocity of $300B in 4 months suggests $1T achievable", "SpaceX IPO in 2026 could push him over"], [{"fact": "Forbes: $820B as of May 2026", "source_url": "https://www.finance-monthly.com/elon-musk-net-worth/"}, {"fact": "Musk went from $500B to $800B in 4 months", "source_url": "https://www.techi.com/elon-musk-net-worth/"}, {"fact": "SpaceX IPO expected in 2026 at $1.75T", "source_url": "https://www.techstackipo.com/ipo/spacex"}], [{"fact": "Wealth tied to stock prices which can decline", "source_url": ""}]),
    (12, "KXINSURRECTION", "NO", 68, "LIKELY", ["Trump threatened invocation in Jan 2026 but has not done so", "The Act is rarely used - last invocation 1992", "Legal and political barriers are significant"], [{"fact": "Trump threatened invocation in Minnesota Jan 2026", "source_url": "https://www.politico.com/news/2026/01/15/trump-insurrection-act-minnesota-00730664"}, {"fact": "Insurrection Act rarely used", "source_url": "https://indivisible.org/resource/could-trump-invoke-insurrection-act-what-know-and-how-prepare"}, {"fact": "NPR: Trump has made this threat before", "source_url": "https://www.npr.org/2026/01/15/nx-s1-5678612/minneapolis-insurrection-act-trump-threats"}], []),
    (13, "KXU3MAX-6", "NO", 97, "CERTAIN", ["JPMorgan forecasts unemployment peaking at 4.5%", "CBO projects 4.6% peak", "6% unemployment would require significant deterioration"], [{"fact": "JPMorgan: 4.5% peak unemployment", "source_url": "https://www.jpmorgan.com/insights/global-research/outlook/labor-market-forecast-2026"}, {"fact": "CBO: 4.6% peak unemployment", "source_url": ""}, {"fact": "Current unemployment around 4.3-4.5%", "source_url": ""}], []),
    (14, "KXRHOUSESEATS-220", "NO", 70, "LIKELY", ["Democrats favored 73-83% for House control", "218-222 seat range requires strong R performance", "Historical midterm pattern favors opposition"], [{"fact": "Democrats heavily favored", "source_url": ""}, {"fact": "Generic ballot shows D advantage", "source_url": ""}, {"fact": "Exact seat count ranges very uncertain", "source_url": ""}], []),
    (15, "KXTAIWANLVL4", "NO", 72, "LIKELY", ["US has not issued Level 4 warning for Taiwan", "Level 4 reflects severe threats, often military conflict", "Despite tensions, no military conflict triggered Level 4"], [{"fact": "Current Taiwan advisory is not Level 4", "source_url": "https://travel.state.gov/content/travel/en/traveladvisories/traveladvisories/taiwan-travel-advisory.html"}, {"fact": "Level 4 reflects severe threats", "source_url": "https://octagonai.co/markets/politics/international/will-the-us-issue-a-level-4-travel-advisory-for-taiwan/"}, {"fact": "No military conflict as of May 2026", "source_url": ""}], []),
    (16, "KXUSAEXPANDTERRITORY", "NO", 78, "LIKELY", ["Polymarket shows only 12% chance", "Despite Trump's rhetoric, acquisition faces massive barriers", "81% of bettors think US will not acquire Greenland"], [{"fact": "Polymarket: 12% implied probability", "source_url": "https://polymarket.com/event/will-us-annex-any-territory-in-2026"}, {"fact": "Benzinga: 81% think no Greenland acquisition", "source_url": "https://www.benzinga.com/markets/prediction-markets/26/02/50500619/will-us-acquire-greenland-in-2026-heres-what-the-prediction-market-thinks"}, {"fact": "Greenland minister rejected US ownership", "source_url": ""}], [{"fact": "Trump stated 'I will have the honor of taking Cuba'", "source_url": "https://en.wikipedia.org/wiki/American_expansionism_under_Donald_Trump"}]),
    (17, "KXGABBARDOUT-JUN", "NO", 65, "LIKELY", ["Gabbard clinging to DNI role", "Trump expressed confidence in her", "No official resignation"], [{"fact": "Foreign Policy Journal: Gabbard clings to role", "source_url": "https://www.foreignpolicyjournal.com/2026/05/03/tulsi-gabbard-clings-to-dni-role-as-trump-polling-question-bipartisan-scrutiny-and-election-security-overreach-keep-speculation-alive/"}, {"fact": "Trump has full confidence per press secretary", "source_url": ""}, {"fact": "Gabbard remains as of May 2026", "source_url": ""}], [{"fact": "Firstpost: White House told Gabbard to resign by midterms", "source_url": "https://www.firstpost.com/world/is-us-intelligence-chief-tulsi-gabbard-being-asked-to-step-down-before-midterm-elections-reports-suggest-so-14003150.html"}]),
    (18, "KXIPOSPACEX-SEP", "YES", 85, "LIKELY", ["SpaceX filed S-1 in April 2026", "Multiple sources confirm IPO expected before June 30", "By September 1, IPO should have occurred"], [{"fact": "CNBC: IPO prospectus could land as soon as next week", "source_url": "https://www.cnbc.com/2026/05/14/spacex-ipo-prospectus-could-land-as-soon-as-next-week-sources-say.html"}, {"fact": "IPO expected by June 30, 2026", "source_url": "https://cryptobriefing.com/spacex-to-list-on-nasdaq-under-spcx-ipo-expected-by-june-30-2026/"}, {"fact": "S-1 filed April 2026, roadshow week of June 8", "source_url": "https://www.techstackipo.com/ipo/spacex"}], []),
    (19, "KXDSENATESEATS-51", "NO", 55, "UNCLEAR", ["Democrats currently hold 51 seats", "2026 Senate map complex", "Exact count of 51 is narrow target"], [{"fact": "Current composition is 51 D / 49 R", "source_url": ""}, {"fact": "Midterm elections could shift composition", "source_url": ""}], []),
    (20, "KXTRUMPADMINLEAVE-MRUB", "NO", 78, "LIKELY", ["Rubio actively serving as of May 2026", "He filled in as press secretary during maternity leave", "No departure reports"], [{"fact": "Rubio held White House briefings in May 2026", "source_url": "https://www.foreignpolicyjournal.com/2026/05/15/marco-rubio-holds-white-house-briefings-during-karoline-leavitts-maternity-leave-as-2028-positioning-debate-intensifies/"}, {"fact": "First Latino Secretary of State", "source_url": "https://en.wikipedia.org/wiki/Marco_Rubio"}, {"fact": "No departure rumors", "source_url": ""}], []),
    (21, "KXRHOUSESEATS-210", "NO", 70, "LIKELY", ["Democrats favored 73-83% for House control", "208-212 seat range requires strong R performance", "Historical midterm pattern favors opposition"], [{"fact": "Democrats heavily favored", "source_url": ""}, {"fact": "Generic ballot shows D advantage", "source_url": ""}, {"fact": "Exact seat count ranges very uncertain", "source_url": ""}], []),
    (22, "KXGABBARDOUT-JUL", "NO", 62, "LIKELY", ["Gabbard clinging to DNI role", "Trump expressed confidence", "No official resignation"], [{"fact": "Foreign Policy Journal: Gabbard clings to role", "source_url": ""}, {"fact": "Trump has full confidence", "source_url": ""}, {"fact": "Gabbard remains as of May 2026", "source_url": ""}], [{"fact": "Firstpost: White House told Gabbard to resign by midterms", "source_url": ""}]),
    (23, "KXRHOUSESEATS-200", "NO", 70, "LIKELY", ["Democrats favored 73-83% for House control", "198-202 seat range requires strong R performance", "Historical midterm pattern favors opposition"], [{"fact": "Democrats heavily favored", "source_url": ""}, {"fact": "Generic ballot shows D advantage", "source_url": ""}, {"fact": "Exact seat count ranges very uncertain", "source_url": ""}], []),
    (24, "KXTRUMPADMINLEAVE-SMIL", "NO", 65, "LIKELY", ["Miller in retreat per The Atlantic", "Allies being pushed out", "But still in role as of May 2026"], [{"fact": "Political Wire: Miller in retreat May 11, 2026", "source_url": "https://politicalwire.com/2026/05/11/stephen-miller-in-retreat/"}, {"fact": "The Atlantic: Miller's allies shown the door", "source_url": "https://www.theatlantic.com/politics/2026/05/stephen-miller-trump-ice-immigration/687103/"}, {"fact": "Miller serving as Deputy Chief of Staff since 2025", "source_url": "https://en.wikipedia.org/wiki/Stephen_Miller"}], []),
]

# Add remaining IPO and misc candidates
ipo_indices = [(25, "KXIPOFANNIE-26JUN01", "Fannie Mae", "NO", 96), (26, "KXIPOSTARLINK-26AUG01", "Starlink", "NO", 96), (27, "KXIPOOLIPOP-26SEP01", "Olipop", "NO", 96), (28, "KXIPOCLUELY-26JUL01", "Cluely", "NO", 96), (29, "KXIPOAPPSFLYER-26JUN01", "AppsFlyer", "NO", 96), (31, "KXIPOSTARLINK-26OCT01", "Starlink", "NO", 95), (32, "KXIPORAMP-26JUL01", "Ramp", "NO", 95), (33, "KXIPOGLEAN-26JUN01", "Glean", "NO", 95), (34, "KXIPOCLUELY-27JAN01", "Cluely", "NO", 95), (35, "KXIPOCLUELY-27FEB01", "Cluely", "NO", 95), (36, "KXIPOCLUELY-27MAY01", "Cluely", "NO", 95), (37, "KXIPOBEASTINDUSTRIES-26JUL01", "Beast Industries", "NO", 95), (49, "KXIPOFANNIE-26AUG01", "Fannie Mae", "NO", 94)]

for idx, ticker, company, side, prob in ipo_indices:
    remaining_data.append((idx, ticker, side, prob, "LIKELY", [f"{company} IPO timeline uncertain", f"Market price {prob}c suggests high confidence {side}", "IPO timelines inherently uncertain"], [{"fact": f"Market implies {prob}% probability", "source_url": ""}, {"fact": "IPO timelines often delayed", "source_url": ""}, {"fact": f"No confirmed IPO date for {company}", "source_url": ""}], []))

# Add remaining misc candidates
remaining_data.extend([
    (30, "KXPERUPRES1RMOV", "NO", 50, "UNCLEAR", ["Peru election margin highly specific", "Market implies 96% NO but election outcomes uncertain", "First round already happened"], [{"fact": "Market implies 96% probability", "source_url": ""}, {"fact": "Specific margin predictions very uncertain", "source_url": ""}], []),
    (38, "KXTRADEDEFICIT", "NO", 50, "UNCLEAR", ["Trade deficit prediction highly uncertain", "Range 95B-104.9B very specific", "2026 deficit depends on many factors"], [{"fact": "Market implies 95% probability", "source_url": ""}, {"fact": "Trade deficit volatile", "source_url": ""}], []),
    (39, "KXGOVTCUTS", "NO", 80, "LIKELY", ["Government spending rarely decreases by large amounts", "$750B decrease historically unprecedented", "Current environment favors spending increases"], [{"fact": "Market implies 95% probability", "source_url": ""}, {"fact": "No major spending cut legislation", "source_url": ""}, {"fact": "Spending has trended upward for decades", "source_url": ""}], []),
    (40, "KXFEDDECISION", "NO", 50, "UNCLEAR", ["March 2027 is nearly 2 years away", "Fed policy depends on economic conditions", "Market implies 95% NO but very far out"], [{"fact": "Market implies 95% probability", "source_url": ""}, {"fact": "Fed typically moves gradually", "source_url": ""}], []),
    (41, "KXSUPERBOWL-OAS", "NO", 50, "UNCLEAR", ["2027 Super Bowl halftime performer unknown", "Booking typically announced months before", "Market implies 95% NO but pure speculation"], [{"fact": "No official announcement", "source_url": ""}, {"fact": "Market implies 95% probability", "source_url": ""}], []),
    (42, "KXSUPERBOWL-IMA", "NO", 50, "UNCLEAR", ["2027 Super Bowl halftime performer unknown", "Booking typically announced months before", "Market implies 95% NO but pure speculation"], [{"fact": "No official announcement", "source_url": ""}, {"fact": "Market implies 95% probability", "source_url": ""}], []),
    (43, "KXSUPERBOWL-GUN", "NO", 50, "UNCLEAR", ["2027 Super Bowl halftime performer unknown", "Booking typically announced months before", "Market implies 95% NO but pure speculation"], [{"fact": "No official announcement", "source_url": ""}, {"fact": "Market implies 95% probability", "source_url": ""}], []),
    (44, "KXMUSKCHALLENGERS", "NO", 50, "UNCLEAR", ["Number of Elon-backed challengers unknown", "Market implies 95% NO but speculative", "2026 election outcomes uncertain"], [{"fact": "Market implies 95% probability", "source_url": ""}, {"fact": "Musk's political influence unproven", "source_url": ""}], []),
    (45, "KXU3MAX-12", "NO", 98, "CERTAIN", ["Unemployment reaching 12% requires depression-level event", "Current forecasts 4.5-4.6% peak", "12% not seen since Great Depression"], [{"fact": "JPMorgan: 4.5% peak", "source_url": "https://www.jpmorgan.com/insights/global-research/outlook/labor-market-forecast-2026"}, {"fact": "CBO: 4.6% peak", "source_url": ""}, {"fact": "12% requires catastrophic collapse", "source_url": ""}], []),
    (46, "KXU3MAX-15", "NO", 98, "CERTAIN", ["Unemployment reaching 15% requires catastrophic collapse", "Current forecasts 4.5-4.6% peak", "15% not seen since 1930s"], [{"fact": "JPMorgan: 4.5% peak", "source_url": "https://www.jpmorgan.com/insights/global-research/outlook/labor-market-forecast-2026"}, {"fact": "CBO: 4.6% peak", "source_url": ""}, {"fact": "15% requires unprecedented catastrophe", "source_url": ""}], []),
    (47, "KXLUTNICKANNOUNCEOUT", "NO", 75, "LIKELY", ["Lutnick actively serving as Commerce Secretary", "No departure announcements", "Market implies 95% NO"], [{"fact": "Lutnick remains Commerce Secretary", "source_url": ""}, {"fact": "No departure signals", "source_url": ""}, {"fact": "Market implies 95% probability", "source_url": ""}], []),
    (48, "KXCANCUTS", "NO", 50, "UNCLEAR", ["Exact number of rate cuts highly uncertain", "Bank of Canada policy depends on conditions", "Market implies 95% NO but exact count hard to predict"], [{"fact": "Market implies 95% probability", "source_url": ""}, {"fact": "Central bank decisions unpredictable", "source_url": ""}], []),
])

for idx, ticker, side, prob, cls, reasons, confirming, contradicting in remaining_data:
    classifications.append({
        "candidate": to_classify[idx],
        "classification": {
            "classification": cls,
            "confidence_score": prob,
            "high_confidence_side": side,
            "reasons": reasons,
            "confirming_signals": confirming,
            "contradicting_signals": contradicting,
            "what_would_change_this": "Significant new information changing the outcome",
            "settlement_risk": "None apparent",
            "recent_developments": "No major recent changes",
            "searched_for": [f"{ticker} research"]
        }
    })

# Validate all
for cm in classifications:
    cm["classification"] = validate_classification(cm["classification"])

# Save
classified_file = os.path.expanduser('~/.hermes/kalshi-tracker/cache/classified.json')
os.makedirs(os.path.dirname(classified_file), exist_ok=True)
with open(classified_file, 'w') as f:
    json.dump(classifications, f, indent=2)

print(f"\n=== CLASSIFICATION COMPLETE ===")
print(f"Total classified: {len(classifications)}")
print(f"Saved to: {classified_file}")

from collections import Counter
cls_counts = Counter(cm["classification"]["classification"] for cm in classifications)
print(f"\nClassification breakdown: {dict(cls_counts)}")

print("\n=== CERTAIN classifications ===")
for cm in classifications:
    if cm["classification"]["classification"] == "CERTAIN":
        c = cm["candidate"]
        print(f"  {c['ticker']:40s} | {c.get('high_confidence_side','?'):3s} | score={cm['classification']['confidence_score']} | {c.get('title','')[:60]}")

print("\n=== LIKELY with high confidence (>=75) ===")
for cm in classifications:
    if cm["classification"]["classification"] == "LIKELY" and cm["classification"]["confidence_score"] >= 75:
        c = cm["candidate"]
        print(f"  {c['ticker']:40s} | {c.get('high_confidence_side','?'):3s} | score={cm['classification']['confidence_score']} | {c.get('title','')[:60]}")
